### ISSUE TITLE
Update resources other than FamPlex

### ISSUE THREAD

**Issue by bgyori** [clulab/bioresources#23]
Looking at some of the current kb files, except for PubChem, they are all ~4 years old. There is pretty rapid change in these resources (GO, HGNC, UP, CHEBI in my experience all drift fairly fast over time), and I have found that REACH produces outdated/withdrawn IDs in some namespaces. Therefore, I think it would make sense to update resources across the board. 

Among other things, these updates would also affect the way the FamPlex export is created, since, as we discussed in #22, what goes into an overrides file depends on the entries appearing in other resources. So if we agree that this more general update should be done, then #22 would have to be done after that.

**Comment by MihaiSurdeanu** [comment]
Good point. 
These were contributed by different members of the original Reach team, so I think I need their help to get (and document!) the new files.
@enoriega, @hickst: can you please help with this? I think @enoriega provided the files related to context, and @hickst the others. Note: we only need the files used in this file:
https://github.com/clulab/bioresources/blob/master/ner_kb.config
@bgyori is handling the BE* ones.

It would be ideal if you could provide a script to (or a document that tells us how to) collect these files. Many many thanks!

**Comment by hickst** [comment]
Wow, seems like ancient history but it's actually been about 4 years since we created these KBs....I remember it being a very manual process whereby I would locate and get access to a resource, download it, and write some bespoke script to extract the relevant information. The resources did not then use a standard format (were mostly textual) and so we had to figure out how to parse the info out of them. I will look for the various scripts that I used.

**Comment by MihaiSurdeanu** [comment]
I really appreciate it @hickst !

**Comment by enoriega** [comment]
Out of the list of entities on the file, I recognize three of them that I introduced and still survive:

- _Species_, which is borrowed from the Linnaeus Project's NER, that hasn't been updated since 2011, therefore we're still up to date. The files are still available at http://linnaeus.sourceforge.net

- _Cell lines_: This is the result of a scraping effort of the [ATCC catalog](https://www.atcc.org/search#q=cell%20lines&sort=relevancy). Unfortunately I couldn't find the scraping script, however this should be relatively simple to code using [Scrapy](https://scrapy.org), which is what I used back in the day.

- _Tissue Type_: This was derived from Uniprot and the file was recently updated as of last December. This should be trivial to read and format to the bioresources input format.

We did document the origin of each KB on the wiki of this repo. https://github.com/clulab/bioresources/wiki/KBs

**Comment by MihaiSurdeanu** [comment]
Thanks @enoriega !

**Comment by bgyori** [comment]
UP has been updated, GO significantly extended and updated, CHEBI restored and updated, and HGNC added as a source of synonyms for human proteins in UP. I think we can call this done for now, and update any of the other resources only if necessary later.
